### ISSUE TITLE
[1.10.2-v3.0b] Multiplayer Server crash

### ISSUE THREAD

**Issue by iou1name** [DoctorWiggles/HelperTools#14]
The mod works fine in single player but every time I try to start my SMP server with it the server crashes before it can start.

latest.log: http://pastebin.com/rT9hsvZ9
crash report: http://pastebin.com/qzjY729m

I'm using:
Minecraft 1.10.2
Forge 12.18.1.2076
HelperTools v3.0b

**Comment by DoctorWiggles** [comment]
Ah thank you, I shouldn't had missed that one :^)
It's been fixed with version 3.0c -> [https://github.com/DoctorWiggles/HelperTools/commit/bce309f5387a8f15f26ee572053e745b2598b172]
https://github.com/DoctorWiggles/HelperTools/releases/tag/(1.10%2C2)-v3.0c
