### ISSUE TITLE
Setup Repository Correctly

### ISSUE THREAD

**Issue by TehNut** [DoctorWiggles/HelperTools#8]
In it's current state, the repository is not "correct" by any means.

First off, repository names should not be changed with every version. This one should just be `HelperTools`. It makes it **_incredibly**_ hard to link to the repository otherwise.

[Here is an example](https://github.com/TehNut/MoreChisels) of a "correct" repository.

What it includes that yours does not:
- A `.gitignore` that stops unwanted files from being uploaded to the repository. [Here](https://github.com/TehNut/MoreChisels/blob/master/.gitignore) is one you can copy. It should keep all files but the ones you need out of the repo.
- A `LICENSE` file. Without that, the source code falls under "[All Rights Reserved](http://en.wikipedia.org/wiki/All_rights_reserved)"
- A `README.md` file that provides basic information.
- The gradle files. Without these, nobody can build your mod unless they manually grab the gradle stuff from another Forge repo.
  - The missing files: `build.gradle`, `../gradle/*`, `gradlew`, and `gradlew.bat`.
- The source folders are in the incorrect directory for a standard gradle project. Correcting these will allow users to setup the workspace correctly.
  - The `../assets/*` folder should be in `../src/main/resources/`
  - The `../helpertools/*` folder should be in `../src/main/java/`

If wanted, I can submit a PR that solves all of these issues except the repository title. Only you can change that.

**Comment by DoctorWiggles** [comment]
Hello, and thank you for pointing these things out. I'm still very new to github and barely know how to use it, I myself have been manually cut and the pasting files from eclipse into github. Any help getting things properly running would be greatly appreciated.

**Comment by TehNut** [comment]
If you give me an hour or so I can put together a PR to fix all the issues as well as explain anything you don't understand.

Edit: Alright, an hour may have been overstated. I got bored.

**Comment by TehNut** [comment]
Closed by #9. If you have questions about anything, feel free to ask.
